# Generated by Django 5.2.13 on 2026-05-05 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='source_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
