# Generated by Django 5.2.13 on 2026-05-07 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_topic_source_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='default_quality_threshold',
            field=models.FloatField(default=0.4),
        ),
        migrations.AddField(
            model_name='topic',
            name='source_mode',
            field=models.CharField(choices=[('automatic', 'Automatic'), ('custom_only', 'Custom only'), ('hybrid', 'Hybrid')], default='automatic', max_length=20),
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField()),
                ('normalized_url', models.URLField()),
                ('source_type', models.CharField(blank=True, max_length=50)),
                ('platform', models.CharField(blank=True, max_length=50)),
                ('validation_status', models.CharField(choices=[('pending', 'Pending'), ('valid', 'Valid'), ('invalid', 'Invalid')], default='pending', max_length=16)),
                ('last_validation_error', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='topics.topic')),
            ],
            options={
                'ordering': ['topic_id', 'id'],
            },
        ),
    ]
