# Generated by Django 5.2.13 on 2026-05-09

from django.db import migrations, models


def migrate_source_modes_forward(apps, schema_editor):
    Topic = apps.get_model("topics", "Topic")
    Topic.objects.filter(source_mode="automatic").update(source_mode="discovery_only")
    Topic.objects.filter(source_mode="custom_only").update(source_mode="curated_only")


def migrate_source_modes_backward(apps, schema_editor):
    Topic = apps.get_model("topics", "Topic")
    Topic.objects.filter(source_mode="discovery_only").update(source_mode="automatic")
    Topic.objects.filter(source_mode="curated_only").update(source_mode="custom_only")


class Migration(migrations.Migration):

    dependencies = [
        ("topics", "0003_topic_default_quality_threshold_topic_source_mode_and_more"),
    ]

    operations = [
        migrations.RunPython(migrate_source_modes_forward, migrate_source_modes_backward),
        migrations.AlterField(
            model_name="topic",
            name="source_mode",
            field=models.CharField(
                choices=[
                    ("discovery_only", "Discovery only"),
                    ("curated_only", "Curated only"),
                    ("hybrid", "Hybrid"),
                ],
                default="discovery_only",
                max_length=20,
            ),
        ),
    ]
