# Generated by Django 5.2.13 on 2026-05-09

from django.db import migrations, models
import django.db.models.deletion
from django.db.models import Q


def backfill_topic_sources_from_topic_source_url(apps, schema_editor):
    Topic = apps.get_model("topics", "Topic")
    TopicSource = apps.get_model("topics", "TopicSource")

    TopicSource.objects.filter(origin="").update(origin="curated")

    for topic in Topic.objects.exclude(source_url__isnull=True).exclude(source_url=""):
        source_url = str(topic.source_url or "").strip()
        if not source_url:
            continue

        existing = TopicSource.objects.filter(topic=topic, url=source_url).first()
        if existing is None:
            TopicSource.objects.create(
                topic=topic,
                name="",
                url=source_url,
                normalized_url=source_url,
                source_type="",
                origin="manual",
                platform="",
                validation_status="pending",
                last_validation_error="",
                is_active=True,
            )
        elif not existing.origin:
            existing.origin = "manual"
            existing.save(update_fields=["origin", "updated_at"])


class Migration(migrations.Migration):

    dependencies = [
        ("topics", "0004_topic_source_mode_discovery_abstraction"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Source",
            new_name="TopicSource",
        ),
        migrations.AlterModelTable(
            name="topicsource",
            table="topics_source",
        ),
        migrations.AddField(
            model_name="topicsource",
            name="name",
            field=models.CharField(blank=True, default="", max_length=160),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="topicsource",
            name="origin",
            field=models.CharField(
                choices=[("manual", "Manual"), ("discovered", "Discovered"), ("curated", "Curated")],
                default="curated",
                max_length=16,
            ),
        ),
        migrations.RenameField(
            model_name="topicsource",
            old_name="original_url",
            new_name="url",
        ),
        migrations.RunPython(backfill_topic_sources_from_topic_source_url, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="topicsource",
            constraint=models.UniqueConstraint(
                condition=Q(is_active=True),
                fields=("topic", "normalized_url"),
                name="unique_active_topic_source_url",
            ),
        ),
    ]
