# Generated by Django 5.2.13 on 2026-05-13

from django.db import migrations, models


def backfill_topic_display_order(apps, schema_editor):
    Topic = apps.get_model("topics", "Topic")
    users = (
        Topic.objects.order_by()
        .values_list("user_id", flat=True)
        .distinct()
    )
    for user_id in users:
        ordered_topics = list(
            Topic.objects.filter(user_id=user_id).order_by("name", "id")
        )
        for index, topic in enumerate(ordered_topics, start=1):
            topic.display_order = index
            topic.save(update_fields=["display_order", "updated_at"])


class Migration(migrations.Migration):

    dependencies = [
        ("topics", "0005_topicsource_persistent_multi_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="display_order",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.RunPython(backfill_topic_display_order, migrations.RunPython.noop),
    ]
