# Generated by Django 5.2.13 on 2026-05-13 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0006_topic_display_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('topics.topicsource',),
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['display_order', 'name']},
        ),
        migrations.AlterField(
            model_name='topic',
            name='source_mode',
            field=models.CharField(choices=[('discovery_only', 'new only'), ('curated_only', 'saved only'), ('hybrid', 'saved & new')], default='discovery_only', max_length=20),
        ),
    ]
