# Generated by Django 5.2.13 on 2026-04-28 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('digests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_text', models.TextField()),
                ('hook_variants', models.JSONField(default=list)),
                ('cta_variants', models.JSONField(default=list)),
                ('hashtags', models.JSONField(default=list)),
                ('carousel_outline', models.JSONField(blank=True, default=list)),
                ('validation_report', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('digest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content_package', to='digests.digest')),
            ],
        ),
    ]
