# Generated by Django 5.2.13 on 2026-05-05 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packaging', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentpackage',
            options={'ordering': ['-created_at']},
        ),
    ]
