# Generated by Django 5.2.13 on 2026-04-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digestrun',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('collecting', 'Collecting'), ('processing', 'Processing'), ('generating_digest', 'Generating digest'), ('packaging', 'Packaging'), ('completed', 'Completed'), ('partial_failed', 'Partial failed'), ('failed', 'Failed')], default='pending', max_length=32),
        ),
    ]
