# Generated by Django 5.2.13 on 2026-05-06 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digests', '0002_alter_digestrun_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='digest',
            name='payload',
            field=models.JSONField(default=dict),
        ),
    ]
