# Generated by Django 5.2.13 on 2026-05-06 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digests', '0003_digest_payload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='digest',
            name='key_points',
        ),
        migrations.RemoveField(
            model_name='digest',
            name='sources',
        ),
        migrations.RemoveField(
            model_name='digest',
            name='summary',
        ),
    ]
