# Generated by Django 5.2.13 on 2026-05-07 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digests', '0004_remove_digest_key_points_remove_digest_sources_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='digestrun',
            name='audience_key',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='digestrun',
            name='quality_threshold_used',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='digestrun',
            name='result_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='digestrun',
            name='source_mode',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='digestrun',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('collecting', 'Collecting'), ('processing', 'Processing'), ('generating_digest', 'Generating digest'), ('packaging', 'Packaging'), ('completed', 'Completed'), ('insufficient_quality', 'Insufficient quality'), ('partial_failed', 'Partial failed'), ('failed', 'Failed')], default='pending', max_length=32),
        ),
    ]
