# Generated by Django 5.2.13 on 2026-05-20 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digests', '0007_usedarticle_repeat_visibility'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usedarticle',
            options={'ordering': ['-last_used_at', '-id']},
        ),
    ]
